name: 'PRE LLM PR Reviewer'
description: 'Automatically review pull requests using LLM through bellman library'
author: 'Modular Finance'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  bellman-key:
    description: 'API key for LLM service'
    required: true
  bellman-url:
    description: 'url to bellman service'
    required: true
  bellman-model:
    description: 'LLM model to use for review'
    required: false
    default: 'VertexAI/gemini-2.0-flash'
  system-prompt-addition:
    description: 'Additional context to add to system prompt'
  system-prompt:
    description: 'System prompt to use for review'

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Get PR Number
      shell: bash
      id: get-pr-number
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ] || [ "${{ github.event_name }}" == "pull_request_target" ]; then
          echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
        elif [ "${{ github.event_name }}" == "issue_comment" ]; then
          echo "pr_number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
        else
          echo "Unsupported event type: ${{ github.event_name }}"
          exit 1
        fi

    - name: Build and run reviewer
      shell: bash
      env:
        BELLMAN_KEY: ${{ inputs.bellman-key }}
        BELLMAN_MODEL: ${{ inputs.bellman-model }}
        BELLMAN_URL: ${{ inputs.bellman-url }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_PR_NUMBER: ${{ steps.get-pr-number.outputs.pr_number }}
        SYSTEM_PROMPT: ${{ inputs.system-prompt }}
        SYSTEM_PROMPT_ADDITION: ${{ inputs.system-prompt-addition }}
      run: |
        cd ${{ github.action_path }}
        go mod tidy
        go build -o pre main.go
        ./pre

branding:
  icon: 'eye'
  color: 'blue'