name: Bellman PR Bot

on:
  pull_request_review_comment:
    types:
      - created

jobs:
  pre-llm-review:
    if: startsWith(github.event.comment.body, '/bellman')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Review PR with LLM
        uses: modfin/pre@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          bellman-key: ${{ secrets.BELLMAN_KEY }}
          bellman-url: ${{ secrets.BELLMAN_URL }}
          bellman-model: 'VertexAI/gemini-2.0-flash'
          system-prompt-addition: ${{ github.event.comment.body }}