name: Bellman PR Evaluator

on:
  pull_request:
    types: [opened]

jobs:
  pre-llm-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Review PR with LLM
        uses: modfin/pre@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          bellman-key: ${{ secrets.BELLMAN_KEY }}
          bellman-url: ${{ secrets.BELLMAN_URL }}
          bellman-model: 'VertexAI/gemini-2.0-flash'
#          system-prompt: |-
#            You are a software developer who is reviewing a pull request.
#            Highlight any potential bugs, but dont overdo it and respont with LGTM if there are no major issues.




